### PR TITLE
post-release: automatic testing (continuous integration) of build on macOS with gcc+gfortran

### PR DESCRIPTION
**Pull request by climbfuji**
This PR adds an action script to enable continuous integration (automatic testing) of the NCEPLIBS-external build on macOS with gcc+gfortran.

### CODE REVIEW

**Comment by climbfuji** [comment]
I tested this CI script on my fork, and for some reasons it did run the test automatically when I created the PR. No idea why it doesn't do it here, maybe we just need to merge it and see what happens?

**Comment by climbfuji** [comment]
It triggered the test on my fork (see https://github.com/climbfuji/NCEPLIBS-external-1/runs/487972917?check_suite_focus=true). Let's wait for it to finish before taking any further steps.

**Comment by kgerheiser** [comment]
This is really cool. I approve

**Comment by climbfuji** [comment]
> This is really cool. I approve

Thanks! Let's hope it registers correctly after merging.

**Pull request merged**
