### PR TITLE
release/public-v2: turn option DEPLOY on by default, update documentation

### PR DESCRIPTION
**Pull request by climbfuji**
This PR
- turns on the option to deploy modules files by default
- updates the documentation for the changes in this PR and in https://github.com/NOAA-EMC/NCEPLIBS/pull/148 for all platforms (NCEPLIBS PR has been committed, new hash for release/public-v2 is https://github.com/NOAA-EMC/NCEPLIBS/commit/f4482d40c8db1935a6a475334675ecdcac7d80a4)
    - not yet updated: Docker container
- remove manual NCEPLIBS-external cmake config file (left from release/public-v1)
- create libjpeg and jasper modules

This has been tested on all platforms (with ufs-weather-model as in https://github.com/ufs-community/ufs-weather-model/pull/248) except odin.intel, wcoss_cray, Docker container:

- cheyenne_gnu
- cheyenne_intel
- gaea_intel
- hera_gnu
- hera_intel
- jet_intel
- macos_clanggfortran
- macos_gccgfortran
- redhat_gnu (AWS)
- orion_intel
- stampede_intel
- ubuntu_gnu (AWS)
- wcoss_dell_p3

### CODE REVIEW

**Review by kgerheiser — APPROVED** [review]

**Comment by RatkoVasic-NOAA** [comment]
I'm testing it on WCOSS-Dell. I had to add two lines for the compilation of the https://github.com/NOAA-EMC/NCEPLIBS-external:
   587  18:25   module use /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/soft/modulefiles
   588  18:25   module load netcdf_parallel/4.7.4

**Comment by climbfuji** [comment]
> I'm testing it on WCOSS-Dell. I had to add two lines for the compilation of the https://github.com/NOAA-EMC/NCEPLIBS-external:
> 587 18:25 module use /gpfs/dell2/emc/modeling/noscrub/emc.nemspara/soft/modulefiles
> 588 18:25 module load netcdf_parallel/4.7.4

Thanks, I'll add them, hopefully correct. Further down, for building the model. You shouldn't (have to) load `esmf/8.0.0_ParallelNetCDF`, because this is built by NCEPLIBS-external. Can you try that, please?

**Comment by RatkoVasic-NOAA** [comment]
I still haven't got to the model. It is failing in NCEPLIBS:
-- Installing NCEPLIBS from /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS/COMPONENTS
-- Installing NCEPLIBS at /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS-external-1
-- Installing NCEPLIBS modulefiles at /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS-external-1/modules, NCEPLIBS shell scripts at /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS-external-1/bin
CMake Error at CMakeLists.txt:259 (find_package):
  By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NetCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NetCDF" with any
  of the following names:

    NetCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
  "NetCDF_DIR" to a directory containing one of the above files.  If "NetCDF"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by climbfuji** [comment]
> I still haven't got to the model. It is failing in NCEPLIBS:
> -- Installing NCEPLIBS from /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS/COMPONENTS
> -- Installing NCEPLIBS at /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS-external-1
> -- Installing NCEPLIBS modulefiles at /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS-external-1/modules, NCEPLIBS shell scripts at /gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS-external-1/bin
> CMake Error at CMakeLists.txt:259 (find_package):
> By not providing "FindNetCDF.cmake" in CMAKE_MODULE_PATH this project has
> asked CMake to find a package configuration file provided by "NetCDF", but
> CMake did not find one.
> 
> Could not find a package configuration file provided by "NetCDF" with any
> of the following names:
> 
> ```
> NetCDFConfig.cmake
> netcdf-config.cmake
> ```
> 
> Add the installation prefix of "NetCDF" to CMAKE_PREFIX_PATH or set
> "NetCDF_DIR" to a directory containing one of the above files. If "NetCDF"
> provides a separate development package or SDK, be sure it has been
> installed.

You didn't clone NCEPLIBS with the `--recursive` option, I suppose. That means the `CMakeModules` submodule/subdirectory is missing.

**Comment by RatkoVasic-NOAA** [comment]
600  18:49   git clone --recursive https://github.com/NOAA-EMC/NCEPLIBS
   604  18:49   git branch -a
   605  18:49   git chackout release/public-v2

Maybe wrong branch?

**Comment by climbfuji** [comment]
> 600 18:49 git clone --recursive https://github.com/NOAA-EMC/NCEPLIBS
> 604 18:49 git branch -a
> 605 18:49 git chackout release/public-v2
> 
> Maybe wrong branch?

I think this leaves you with the submodules (none) of the develop branch. You need to do
```
git clone --recursive -b release/public-v2 https://github.com/NOAA-EMC/NCEPLIBS
```

**Comment by RatkoVasic-NOAA** [comment]
will try now
It's compiling 
make failed somewhere, I'll start from the beginning.

make[2]: Leaving directory `/gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS/build'
[ 80%] Built target crtm
make[1]: Leaving directory `/gpfs/dell2/emc/modeling/noscrub/Ratko.Vasic/wrk/tmp/NCEPLIBS-external-1/doc/src/NCEPLIBS/build'
make: *** [all] Error 2

**Comment by RatkoVasic-NOAA** [comment]
Scanning dependencies of target NEMS.exe
[100%] Building Fortran object CMakeFiles/NEMS.exe.dir/NEMS/src/MAIN_NEMS.F90.o
[100%] Linking Fortran executable NEMS.exe
[100%] Built target NEMS.exe

**Comment by climbfuji** [comment]
> Scanning dependencies of target NEMS.exe
> [100%] Building Fortran object CMakeFiles/NEMS.exe.dir/NEMS/src/MAIN_NEMS.F90.o
> [100%] Linking Fortran executable NEMS.exe
> [100%] Built target NEMS.exe

Great, thanks for that. Where the instructions I sent you by email complete? I need to update the README file in this PR. Thanks!

**Pull request merged**
