### PR TITLE
Add Open MPI, update README.md, fix minor bugs in CMakeLists.txt

### PR DESCRIPTION
**Pull request by climbfuji**
- Add Open MPI
- Build wgrib2 executable in addition to wgrib2 library
- Bugfix for CMakeLists.txt: only built jpeg when Jasper is built
- Update README.md

### CODE REVIEW

**Comment by kgerheiser** [comment]
Looks good to me

**Comment by mark-a-potts** [comment]
Looks good to me.

**Comment by climbfuji** [comment]
@kgerheiser @mark-a-potts I am seeing an error in the install step for Jasper (bin/jasper) when it is trying to adjust the RPATH. It doesn't seem to make any difference, and we are not using it. But it would be good to fix it.

**Comment by climbfuji** [comment]
Note: the reason why I added the tarballs for wgrib2 and openmpi instead of running a curl/wget command is that on some systems the firewall doesn't allow that. Users need to do the git clone recursively elsewhere and sync the entire directory.

**Comment by climbfuji** [comment]
This PR must be merged together with https://github.com/NOAA-EMC/NCEPLIBS/pull/34

**Comment by DusanJovic-NOAA** [comment]
Can we set BUILD_MPI by default to OFF. On most HPC system MPI library will be provided, and on personal computers (laptops/desktops) again more often than not MPI is available via package manager. On systems where MPI is not available user can always set BUILD_MPI to ON explicitly.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA this isn't that easy. When you install openmpi using homebrew on macOS, it compiles everything with the clang compiler (the native one from the OS) unless you find a way to force it to `mpicc -CC=gcc-9`. With the default clang compiler, you get a lot of problems. Similar story for "older" CentOS/Redhat. If you use the package manager version, it's default compiler is gcc-4.8.5 unless I completely miss something. Have you read the README.md in the NCEPLIBS-external (the wiki refers to it) about switching off certain components?

**Comment by climbfuji** [comment]
Oh, and by the way. If I compile openmpi on the mac manually using the exact same commands as inside cmake, and then compile NCEPLIBS-external with -DBUILD_MPI=OFF, I can run chgres_cube.exe and ufs_model.exe without problems. On macOS, I still get a crash in the post, but I am working on this. Just need to fix the cmake -> build MPI build first. But as a workaround, please compile openmpi/mpich manually and set -DBUILD_MPI=OFF.

**Comment by DusanJovic-NOAA** [comment]
I have. And I know I can turn off MPI build by ``-DBUILD_MPI=OFF``. My suggestion was that by default it should be OFF and if locally built MPI is needed it can be turned on explicitly. Most common case should be a default.

**Comment by climbfuji** [comment]
> I have. And I know I can turn off MPI build by `-DBUILD_MPI=OFF`. My suggestion was that by default it should be OFF and if locally built MPI is needed it can be turned on explicitly. Most common case should be a default.

Well, I am not sure if it should be OFF, because it will *not* work with the homebrew openmpi on macOS, and on Redhat/CentOS 7 users will end up with a gcc-4.8.5 compiler invoked by mpicc as far as I know (I might be wrong, though). I suggest to do a few more tests before deciding on the best solution.

**Comment by DusanJovic-NOAA** [comment]
It will work with the homebrew on macOS. You just need to set ``-DBUILD_MPI=ON``. Again, the only thing I'm suggesting is different default.

**Comment by climbfuji** [comment]
Ok, here is the deal: When we have finalized the instructions on the wiki, we count how many systems we have that require installing the MPI library, and how many don't. The majority decides if the default is ON or OFF. I assume you will win, in which case I am happy to adjust the instructions and make OFF the default.

**Pull request merged**
