### PR TITLE
CMake wgrib2

### PR DESCRIPTION
**Pull request by kgerheiser**
Add the CMake wgrib2 to NCEPLIBS-external

Also had to change the Jasper version to 1.900.1 because wgrib2 wouldn't build with our 2.x.x version. I think this is correct anyway because it's the version all the supercomputers use.

### CODE REVIEW

**Comment by kgerheiser** [comment]
Seems to work

**Comment by climbfuji** [comment]
Looks promising! I noticed the "work in progess" label. When you think this is good, can you please try to remove the -DBUILD_WGRIB2=OFF from the macOS travis yml files, and see if it works with your changes? We will also need to change the repository for wgrib2 before the release tag 1.1.0 is created, we can't have a release pull code from a private repository.

**Comment by kgerheiser** [comment]
Good catch, didn't realize those were off.

**Comment by kgerheiser** [comment]
And my repo tag is just temporary

**Comment by kgerheiser** [comment]
I merged my wgrib2 changes and updated ExternalProject to use the official repo.

It should be good to go now.

**Comment by climbfuji** [comment]
That looks good - let me check it out and build it locally as well. Stay tuned ...

**Review by climbfuji — APPROVED** [review]
Tested on my macOS with clang+gfortran and with gcc+gfortran. Works like a charm. Not tested yet with NCEPLIBS on top, but this is good to merge.

**Pull request merged**
