### PR TITLE
Update orion documentation (post-release)

### PR DESCRIPTION
**Pull request by climbfuji**
Update orion documentation to make clear that the install directory is user specific. I don't think this needs to go into the release, but we can if you think it is better.

### CODE REVIEW

**Comment by kgerheiser** [comment]
The tests are working

**Comment by climbfuji** [comment]
> The tests are working

Yes they are! They take ages, though. For NCEPLIBS, we could do something similar but quicker: install mpi, netcdf, libpng, jasper, libjpeg using homebrew, i.e. call NCEPLIBS-external to only build esmf and wgrib2, then do the actual NCEPLIBS build. I will do this later today or tomorrow, this is a lot of fun and very useful.

**Comment by climbfuji** [comment]
@arunchawla-NOAA need your decision to either retrofit this into the release tag or not ... thank you!

**Comment by GeorgeVandenberghe-NOAA** [comment]
I have a general NCEPLIBS  public release install  on ORION in /apps/contrib/NCEPLIBS/public.release/NCEPLIBS  ./lib and ./include and ./bin contain the things I built.

**Comment by climbfuji** [comment]
> I have a general NCEPLIBS public release install on ORION in /apps/contrib/NCEPLIBS/public.release/NCEPLIBS ./lib and ./include and ./bin contain the things I built.

This may be confusing. If orion remains a supported but not preconfigured platform, it would be better to *not* have these libraries pre-installed somewhere in my opinion. Please discuss with @arunchawla-NOAA what the best way forward is.

**Comment by climbfuji** [comment]
> > The tests are working
> 
> Yes they are! They take ages, though. For NCEPLIBS, we could do something similar but quicker: install mpi, netcdf, libpng, jasper, libjpeg using homebrew, i.e. call NCEPLIBS-external to only build esmf and wgrib2, then do the actual NCEPLIBS build. I will do this later today or tomorrow, this is a lot of fun and very useful.

@kgerheiser the previous test passed: https://github.com/NOAA-EMC/NCEPLIBS-external/runs/488283413?check_suite_focus=true

**Comment by climbfuji** [comment]
> Retro fit to the tag (one time deal only)

Thanks, done. The new hash for the tag ufs-v1.0.0 is 21ef9ef76c37b8e409f242532ac0811389e25e9f.

**Pull request merged**
