### PR TITLE
New makefile for wgrib2 that allows using external NetCDF

### LINKED ISSUE #44: Build wgrib2 with NetCDF support
wgrib2 is part of the external libraries. For the UFS v1.0.0 release, we had to build wgrib2 without NetCDF support. This is because the wgrib2 build creates its entire software stack based on certain versions of NetCDF (and dependencies in case of NetCDF4), which it also tries to download first (in case of NetCDF4).

There are a few issues related with this approach:
- downloading doesn't work on all systems (firewalls ...)
- the versions of HDF5 and NetCDF don't match what NCEPLIBS-external is using (ours are newer), and the build options aren't exactly the same either
- because we need to build the wgrib2 library and link it into an executable that also links to our NetCDF, this can result in linker errors or bad behavior

What we need in order to build wgrib2 with NetCDF support and without the overhead/danger of building NetCDF twice is an option to tell the wgrib2 build to use existing dependencies if so provided by the user: jasper, zlib, hdf5, netcdf, ...

There are standard/common variables that are used to indicate where those installations can be found, for example:

ZLIB_ROOT
HDF5_ROOT
Jasper_ROOT
NETCDF
NETCDF_FORTRAN (if not installed in NETCDF)

All those ending in _ROOT are following the CMake rules, for NetCDF the community has come up with its own standard before CMake got there.

Users could, for example, indicate to the wgrib2 build system that they do not want to build package A and tell the build system where A can be found.

### PR DESCRIPTION
**Pull request by kgerheiser**
Fixes #44 

I've got basic support for building with external NetCDF. I package a modified makefile and then copy it into grib2 at configure time. It takes environment variables `NETCDF4_LIB_DIR` and `NETCDF4_INCLUDES`. It can also take `HDF5_DIR` and `ZLIB_DIR`, but for our purposes they are all in the same directory.

Currently, I have it set so that NetCDF has to be built because there's some work required in calling `find_package(NetCDF ..)` and then parsing the output to be that of the library directory.

### CODE REVIEW

**Comment by climbfuji** [comment]
@kgerheiser where are we with this PR? Is there anything I can do to help? I would like to get this (including the use of external netCDF) and the use of make instead of cmake for the netCDF installs in. @mark-a-potts FYI. Thanks!

**Comment by climbfuji** [comment]
@kgerheiser we don't need this anymore, right? Given that you are working on NCEPLIBS-wgrib2 [here](https://github.com/NOAA-EMC/NCEPLIBS-wgrib2), this package will become part of the NCEPLIBS and we no longer build wgrib2 as part of NCEPLIBS-external, correct?

**Comment by kgerheiser** [comment]
That's a good question. I think it will remain in NCEPLIBS-externals for now.

**Comment by climbfuji** [comment]
> That's a good question. I think it will remain in NCEPLIBS-externals for now.

Ok, thanks. Then we need to finish this PR so that we can build wgrib2 against the netCDF version that we are compiling one or two steps earlier.

**Comment by kgerheiser** [comment]
But we will instead use the CMake build of wgrib2 from that repo. This PR can be closed.

**Pull request closed without merging**
