### PR TITLE
Add missing dependency on zlib for hdf5, fiz zlib/wgrib2/libjpeg wrong installation directories, set correct compiler flags for ESMF

### PR DESCRIPTION
**Pull request by climbfuji**
- hdf5 depends on zlib, but the dependency is missing in the top-level `CMakeLists.txt`
- on systems where the default library install directory is `lib64`, zlib puts the libraries in the wrong place (see issue https://github.com/NOAA-EMC/NCEPLIBS-external/issues/17 for more details); the solution proposed here is running a script before compiling zlib that uses `sed` to search for and replace the bad code in zlib's `CMakeLists.txt`; this is also the case for wgrib2 and libjpeg
- use the correct compiler flags for ESMF for Intel and GNU

### CODE REVIEW

**Comment by climbfuji** [comment]
If you have a better / more elegant solution, then I will be happy to use it instead of what is proposed here. Thanks!

**Comment by mark-a-potts** [comment]
I am sure that your script could be done through cmake, but I am fine with this approach.

**Comment by climbfuji** [comment]
I was thinking about doing this in cmake, but it makes the CMakeLists.txt unreadable. At least with my cmake skills. If you think this can be done in an elegant way, then I will be happy to use it. Anyway, I am testing the version on orion and cheyenne now.

**Comment by mark-a-potts** [comment]
Would it make sense to just fork zlib and change the CMakeLists.txt file directly in our fork? We could then put in a pull request to zlib.

**Comment by climbfuji** [comment]
@kgerheiser @mark-a-potts this PR is ready as far as I am concerned. Have a good look please. Thanks very much!

**Pull request merged**
